# Generated by Django 5.2.8 on 2025-11-18 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('target_role', models.CharField(blank=True, choices=[('teacher', 'Tanár'), ('student', 'Diák')], help_text='Ha csak tanárra vagy csak diákra értelmes ez a dimenzió, itt megadhatod.', max_length=20, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire_type', models.CharField(choices=[('student_to_teacher', 'Diák → Tanár'), ('teacher_to_student', 'Tanár → Diák')], max_length=30)),
                ('evaluated_role', models.CharField(choices=[('teacher', 'Tanár'), ('student', 'Diák')], max_length=20)),
                ('context', models.CharField(blank=True, help_text='Pl. 2024/25 1. félév, Matematika, 10.A', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('questionnaire_type', models.CharField(choices=[('student_to_teacher', 'Diák → Tanár'), ('teacher_to_student', 'Tanár → Diák')], help_text='Milyen irányú értékelő ívben jelenik meg (diák→tanár / tanár→diák)?', max_length=30)),
                ('question_type', models.CharField(choices=[('scale', 'Likert skála (1–5)'), ('text', 'Szöveges válasz')], default='scale', max_length=10)),
                ('scale_min', models.PositiveSmallIntegerField(default=1)),
                ('scale_max', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(blank=True, help_text='Szöveges kérdésnél opcionális.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='vizsgaremek_app.dimension')),
            ],
            options={
                'ordering': ['questionnaire_type', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vizsgaremek_app.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='vizsgaremek_app.question')),
            ],
            options={
                'unique_together': {('evaluation', 'question')},
            },
        ),
    ]
