# Generated by Django 5.2.8 on 2025-11-18 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vizsgaremek_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Rövid cím, pl. 'Bukási arány', 'Jegyátlag'.", max_length=100)),
                ('value', models.CharField(help_text="Érték szövegesen, pl. '15%', '3.4', '10 fő / 30 fő'.", max_length=100)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_metrics', to='vizsgaremek_app.evaluation')),
            ],
            options={
                'verbose_name': 'Objektív mutató',
                'verbose_name_plural': 'Objektív mutatók',
            },
        ),
    ]
